ci: add lint and cppcheck

diff --git a/.github/workflows/example2.yml b/.github/workflows/example2.yml
--- a/.github/workflows/example2.yml
+++ b/.github/workflows/example2.yml
@@ -13,9 +13,17 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: install g++
-        run: sudo apt install -y g++
+        run: sudo apt install -y g++ cppcheck
+
+      - name: run cppcheck
+        run: |
+          cppcheck hello_world.cpp --output-file=report.txt
+          if [ -s report.txt ]; then # if file is not empty
+            cat report.txt
+            exit 1 # let github action fails
+          fi
 
       - name: check build
         run: |
-          g++ hello_world.cpp -Wall -Werror  -o hello_world
-          # ./hello_world
+          g++ hello_world.cpp -o hello_world
+          ./hello_world
